# Generated by Django 5.2.15 on 2026-06-25 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='显示名称, 如"客服邮箱"', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imap_host', models.CharField(default='imap.qq.com', help_text='IMAP 服务器地址', max_length=200)),
                ('imap_port', models.IntegerField(default=993, help_text='IMAP SSL 端口')),
                ('auth_token', models.TextField(help_text='加密存储的IMAP授权码')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=500)),
                ('uid', models.CharField(blank=True, help_text='IMAP UID', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('sender', models.CharField(blank=True, max_length=300)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('recipients', models.TextField(blank=True, help_text='JSON数组')),
                ('received_at', models.DateTimeField(db_index=True, help_text='邮件头部Date字段')),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailboxes.mailbox')),
            ],
            options={
                'verbose_name': '邮件',
                'verbose_name_plural': '邮件',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['mailbox', '-received_at'], name='mailboxes_e_mailbox_61f16c_idx'), models.Index(fields=['message_id'], name='mailboxes_e_message_b87188_idx')],
            },
        ),
    ]
