# Generated by Django 5.2.15 on 2026-06-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='auth_token',
            field=models.CharField(help_text='IMAP授权码', max_length=200),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='success', max_length=20)),
                ('new_count', models.IntegerField(default=0, help_text='新增邮件数')),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0, help_text='同步耗时（毫秒）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='mailboxes.mailbox')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
