# Generated by Django 5.2.15 on 2026-06-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_alter_mailbox_auth_token_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='encryption',
            field=models.CharField(choices=[('ssl', 'SSL/TLS'), ('starttls', 'STARTTLS'), ('none', '无加密')], default='ssl', help_text='加密方式', max_length=10),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='service_type',
            field=models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', help_text='服务类型', max_length=10),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='imap_host',
            field=models.CharField(default='imap.qq.com', help_text='IMAP/POP3 服务器地址', max_length=200),
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='imap_port',
            field=models.IntegerField(default=993, help_text='端口号'),
        ),
    ]
